steps:
  # 1. Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/smag-backend", "."]
    dir: "backend"

  # 2. Push Image to Container Registry (Auto-creates bucket)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/smag-backend"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "smag-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/smag-backend"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY
